# -*- coding: utf-8 -*-
"""Road_Damage_Detection_Using_YOLOv8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9vhe1Ymct8EwHcAGYKTQEX9sajVW4iH
"""

# Cell 2 — Load TAR file from Drive, extract, and set dataset paths

import tarfile
from pathlib import Path
import os


TAR_PATH = "/content/drive/MyDrive/road-damage-DatasetNinja.tar"   

# Location to extract
EXTRACT_TO = "/content/road_damage_dataset"

# Create folder if not exists
os.makedirs(EXTRACT_TO, exist_ok=True)

# Extract TAR
print("Extracting TAR file... Please wait.")
with tarfile.open(TAR_PATH) as tar:
    tar.extractall(EXTRACT_TO)

print("Extraction completed!")

EXTRACT_TO = Path(EXTRACT_TO)
subdirs = [d for d in EXTRACT_TO.glob("*") if d.is_dir()]

if len(subdirs) == 1:
    DATA_ROOT = subdirs[0]
else:
    DATA_ROOT = EXTRACT_TO

print("DATA_ROOT detected as:", DATA_ROOT)

candidate_imgs = list(DATA_ROOT.rglob("img"))
if len(candidate_imgs) > 0:
    IMG_DIR = candidate_imgs[0]
else:
    raise FileNotFoundError("❌ Could not find 'img/' folder inside extracted TAR")

# Detect annotation JSON (annotations.json OR similar)
possible_jsons = list(DATA_ROOT.rglob("*.json"))
if len(possible_jsons) == 0:
    raise FileNotFoundError("❌ No JSON annotation file found in dataset!")

# Prefer annotations.json
COCO_ANN = None
for j in possible_jsons:
    if "annotations" in j.name.lower():
        COCO_ANN = j
        break
if COCO_ANN is None:
    COCO_ANN = possible_jsons[0]   # fallback to first JSON found

# Detect meta.json
META_FN = None
for j in possible_jsons:
    if "meta" in j.name.lower():
        META_FN = j
        break

print("\nDetected paths:")
print("Image folder:", IMG_DIR)
print("Annotations JSON:", COCO_ANN)
print("Meta JSON:", META_FN)


import json
from collections import Counter, defaultdict
from pprint import pprint
from pathlib import Path # Ensure Path is imported for path operations

new_meta_fn_candidate = EXTRACT_TO / 'meta.json'
if new_meta_fn_candidate.is_file():
    META_FN = new_meta_fn_candidate
else:
    META_FN = None  # Reset META_FN before searching possible_jsons
    for j in possible_jsons:
        if "meta" in j.name.lower():
            META_FN = j
            break

print("META_FN (after updated detection logic):", META_FN)

with open(COCO_ANN, 'r') as f:
    coco = json.load(f)
meta = None
if META_FN:
    with open(META_FN, 'r') as f:
        meta = json.load(f)
    # Step 4: Print a preview of the loaded meta dictionary
    print("\nmeta.json contents (preview):")
    pprint({k: meta[k] for k in list(meta)[:10]})  # show top-level keys
else:
    print("\nWarning: meta.json not found, cannot load meta information.")

images = coco.get("images", [])
annotations = coco.get("annotations", [])
categories = coco.get("categories", [])

print(f"\nCOCO: {len(images)} images, {len(annotations)} annotations, {len(categories)} categories")
catid2name = {c['id']: c['name'] for c in categories}
print("Categories mapping:", catid2name)

# per-class counts
cnt = Counter([a['category_id'] for a in annotations])
print("\nAnnotation counts per class:")
for cid, name in catid2name.items():
    print(f"  {cid} ({name}): {cnt.get(cid,0)}")

# images with width/height check
if len(images) > 0 and 'width' in images[0]:
    wvals = [img['width'] for img in images]
    hvals = [img['height'] for img in images]
    print(f"\nImage size range: width {min(wvals)} - {max(wvals)}, height {min(hvals)} - {max(hvals)}")
else:
    print("\nImages metadata do not include width/height; we'll read them on the fly when needed.")

import json
from collections import Counter, defaultdict
from pprint import pprint
from pathlib import Path

meta = None
if META_FN and META_FN.is_file():
    with open(META_FN, 'r') as f:
        meta = json.load(f)
    print("meta.json loaded successfully.")
else:
    print("Warning: meta.json not found or not accessible.")

# Extract category information from meta.json
meta_categories = meta.get('classes', []) if meta else []
meta_catid2name = {c['id']: c['title'] for c in meta_categories}
meta_catid2color = {c['id']: c['color'] for c in meta_categories}

ann_dir = DATA_ROOT / 'ann'
if not ann_dir.is_dir():
    raise FileNotFoundError(f"❌ Annotation directory not found: {ann_dir}")

all_annotation_files = list(ann_dir.glob('*.json'))

print(f"Found {len(all_annotation_files)} annotation files in {ann_dir}")

combined_images = []
combined_annotations = []

processed_image_filenames = set()

for ann_file_path in all_annotation_files:
    try:
        with open(ann_file_path, 'r') as f:
            image_data = json.load(f)

        # Extract image information
        image_filename = Path(ann_file_path.stem).stem # Remove .json and then original image extension
        image_id = str(hash(image_filename)) # Generate a unique ID for the image if not present

        # For now, we only have file_name and can derive id. Height/width will be read on the fly.
        if image_filename not in processed_image_filenames:
            combined_images.append({
                'file_name': image_filename + '.jpeg', # Assuming .jpeg extension from previous detection
                'id': image_id
            })
            processed_image_filenames.add(image_filename)

        # Extract annotations
        for obj in image_data.get('objects', []):
            # Ensure 'category_id' aligns with our meta_categories
            category_id = obj.get('classId')
            if category_id in meta_catid2name:
                combined_annotations.append({
                    'image_id': image_id,
                    'category_id': category_id,
                    'bbox': [0,0,0,0], # Placeholder, actual bbox depends on geometry_config and points
                    'area': 0, # Placeholder
                    'iscrowd': 0,
                    'id': obj.get('id') # Use object's ID
                })

    except Exception as e:
        print(f"Error processing {ann_file_path}: {e}")

# 3. Aggregate and display comprehensive statistics
print(f"\nAggregated dataset statistics:")
print(f"Total images: {len(combined_images)}")
print(f"Total annotations: {len(combined_annotations)}")

# Prepare categories for display (using meta_catid2name as the source of truth)
print("Categories mapping (from meta.json):", meta_catid2name)

# Per-class counts from combined annotations
annotation_counts = Counter([a['category_id'] for a in combined_annotations])
print("\nAnnotation counts per class:")
for cid, name in meta_catid2name.items():
    print(f"  {cid} ({name}): {annotation_counts.get(cid, 0)}")

print("\nNote: Image width/height will be read on the fly when needed, as individual annotation files do not provide this for the whole dataset.")

print("\n--- Detailed Dataset Summary ---")

# 1. Print total number of images
print(f"Total Images: {len(combined_images)}")

# 2. Print total number of annotations
print(f"Total Annotations: {len(combined_annotations)}")

# 3. Print category ID, name, and color
print("\nCategories and their Colors (from meta.json):")
for cid, name in meta_catid2name.items():
    color = meta_catid2color.get(cid, 'N/A')
    print(f"  ID: {cid}, Name: {name}, Color: {color}")

# 4. Print category ID, name, and annotation count
print("\nAnnotation Counts Per Category:")
for cid, name in meta_catid2name.items():
    count = annotation_counts.get(cid, 0)
    print(f"  ID: {cid}, Name: {name}, Count: {count}")

print("\n--- End Summary ---")

"""#draw boxes + labels"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image

def show_image_with_boxes(image_path, bboxes, labels=None, figsize=(10,8)):
    """
    image_path: Path or str
    bboxes: list of [x,y,w,h] in COCO format OR [x1,y1,x2,y2] if flag bbox_xyxy=True
    labels: optional list of strings to display per box
    """
    img = Image.open(image_path).convert("RGB")
    w, h = img.size
    fig, ax = plt.subplots(1, figsize=figsize)
    ax.imshow(img)
    for i, bb in enumerate(bboxes):
        # assume COCO [x,y,w,h]
        x, y, bw, bh = bb
        rect = patches.Rectangle((x,y), bw, bh, linewidth=2, edgecolor='r', facecolor='none')
        ax.add_patch(rect)
        if labels:
            ax.text(x, y-8, labels[i], color='yellow', fontsize=10, bbox=dict(facecolor='black', alpha=0.5))
    ax.axis('off')
    plt.show()

from random import choice

# build image_id -> list of annotations mapping
# Use combined_annotations instead of annotations
imgid2anns = defaultdict(list)
for ann in combined_annotations:
    imgid2anns[ann['image_id']].append(ann)

# pick 3 random images and show
# Use combined_images instead of images
for _ in range(3):
    if not combined_images:
        print("No images available to display.")
        break

    img_meta = choice(combined_images)

    # The filename in img_meta['file_name'] already includes the .jpeg extension (e.g., 'Y_26600.jpeg')
    actual_image_filename = img_meta['file_name']
    img_path = IMG_DIR / actual_image_filename

    anns_for_img = imgid2anns[img_meta['id']]

    # Bboxes in combined_annotations are placeholders [0,0,0,0]
    # We need to load the actual bbox from the original individual annotation file.
    # This requires re-reading the specific image's annotation JSON

    # The individual annotation file name is the full image filename + '.json'
    # e.g., 'Y_26600.jpeg.json'
    individual_ann_path = DATA_ROOT / 'ann' / (actual_image_filename + '.json')

    if not individual_ann_path.is_file():
        print(f"Warning: Individual annotation file not found for {actual_image_filename} at {individual_ann_path}. Skipping.")
        continue

    try:
        with open(individual_ann_path, 'r') as f:
            current_image_data = json.load(f)

        bboxes = []
        labels = []
        for obj in current_image_data.get('objects', []):
            if obj.get('geometryType') == 'rectangle' and 'points' in obj and 'exterior' in obj['points'] and len(obj['points']['exterior']) == 2:
                x1, y1 = obj['points']['exterior'][0]
                x2, y2 = obj['points']['exterior'][1]
                # Convert to COCO [x,y,w,h] format for show_image_with_boxes
                x = min(x1, x2)
                y = min(y1, y1)
                w = abs(x2 - x1)
                h = abs(y2 - y1)
                bboxes.append([x, y, w, h])

                category_id = obj.get('classId')
                # Use meta_catid2name for labels
                labels.append(meta_catid2name.get(category_id, str(category_id)))
            else:
                print(f"Warning: Skipping non-rectangle or malformed annotation in {individual_ann_path}")

    except Exception as e:
        print(f"Error loading individual annotation for {actual_image_filename}: {e}. Skipping.")
        continue

    print("Showing:", actual_image_filename, " | #annots:", len(bboxes))
    show_image_with_boxes(img_path, bboxes, labels)

"""# Task
The user has approved the current state. The next step is to prepare the dataset in COCO format, which is a standard for object detection. This involves aggregating all image and annotation metadata into a single JSON file.

Here's how we'll accomplish this:

1.  **Extract Category Information**: We will create a `categories` list for the COCO JSON, using the `meta_catid2name` and `meta_catid2color` dictionaries. Each category will include an `id`, `name`, and `supercategory` (which we'll set to a default value if not specified in the `meta.json`).
2.  **Process Images**: We'll iterate through all the `combined_images`. For each image, we will:
    *   Open the image file (using `IMG_DIR` and the image `file_name`) to read its actual `width` and `height`. This is crucial for COCO format.
    *   Update the image dictionary with these dimensions.
3.  **Process Annotations**: For each image, we will then load its corresponding individual annotation JSON file (from `DATA_ROOT / 'ann'`). We'll iterate through the objects within that file:
    *   Extract the bounding box (`bbox`) coordinates in `[x, y, width, height]` format.
    *   Calculate the `area` of the bounding box.
    *   Map the `classId` from the individual annotation to the appropriate `category_id`.
    *   Assign a globally unique `annotation_id`.
    *   Store `image_id`, `category_id`, `bbox`, `area`, `iscrowd` (set to 0), and `id` in the COCO annotation format.
4.  **Assemble COCO JSON**: Finally, we will combine all the extracted `images`, `annotations`, and `categories` lists into a single Python dictionary that adheres to the COCO dataset format. This dictionary can then be saved as a JSON file.

This structured COCO JSON will be essential for feeding the data into most object detection models.

## Prepare Data in COCO Format

### Subtask:
Convert the aggregated image and annotation data into a single COCO-style JSON file.

**Reasoning**:
The subtask requires converting the aggregated image and annotation data into a single COCO-style JSON file. The first step is to initialize the necessary lists and populate the COCO categories based on the existing metadata.
"""

import json
from pathlib import Path
from PIL import Image
import datetime

# 1. Initialize empty lists
coco_images = []
coco_annotations = []

# 2. Create coco_categories from meta_catid2name and meta_catid2color
coco_categories = []
for cid, name in meta_catid2name.items():
    color = meta_catid2color.get(cid, '#000000') # Default to black if no color is found
    coco_categories.append({
        'id': cid,
        'name': name,
        'supercategory': 'road_damage',
        'color': color # Including color for potential visualization later
    })

# 3. Initialize a counter for annotation IDs
annotation_id_counter = 1

print(f"Initialized {len(coco_categories)} COCO categories.")

"""**Reasoning**:
Continuing the COCO format conversion, the next step involves iterating through all aggregated images, reading their dimensions, and then processing their corresponding individual annotation files to extract bounding box details and create COCO-formatted annotations. This process populates the `coco_images` and `coco_annotations` lists.


"""

for img_dict in combined_images:
    # 4.a. Construct the full path to the image file
    img_filename = img_dict['file_name']
    image_path = IMG_DIR / img_filename

    # 4.b. Open the image file to read its actual width and height
    try:
        with Image.open(image_path) as img:
            width, height = img.size
    except FileNotFoundError:
        print(f"Warning: Image file not found: {image_path}. Skipping image.")
        continue

    # 4.c. Update the current image dictionary with these dimensions
    img_dict['width'] = width
    img_dict['height'] = height

    # 4.d. Append the updated image dictionary to coco_images
    coco_images.append(img_dict)

    # 4.e. Construct the full path to the individual annotation JSON file
    # The individual annotation file name is typically 'original_image_name.jpeg.json'
    # The stem of image_filename (e.g., 'Y_26600.jpeg') becomes 'Y_26600'
    # The actual json file is 'Y_26600.jpeg.json'
    individual_ann_path = DATA_ROOT / 'ann' / (img_filename + '.json')

    if not individual_ann_path.is_file():
        print(f"Warning: Individual annotation file not found for {img_filename} at {individual_ann_path}. Skipping annotations for this image.")
        continue

    try:
        # 4.f. Load the contents of this individual annotation JSON file
        with open(individual_ann_path, 'r') as f:
            image_annotations_data = json.load(f)

        # 4.g. Iterate through each object (annotation) in the loaded JSON file
        for obj in image_annotations_data.get('objects', []):
            if obj.get('geometryType') == 'rectangle' and 'points' in obj and 'exterior' in obj['points'] and len(obj['points']['exterior']) == 2:
                # 4.g.i. Extract the bounding box coordinates
                x1, y1 = obj['points']['exterior'][0]
                x2, y2 = obj['points']['exterior'][1]

                # 4.g.ii. Calculate the COCO bounding box format [x, y, width, height]
                x = min(x1, x2)
                y = min(y1, y2)
                bbox_width = abs(x2 - x1)
                bbox_height = abs(y2 - y1)
                coco_bbox = [x, y, bbox_width, bbox_height]

                # 4.g.iii. Calculate the area of the bounding box
                area = float(bbox_width * bbox_height)

                # 4.g.iv. Get the category_id
                category_id = obj.get('classId')
                if category_id not in meta_catid2name: # Ensure category is recognized
                    print(f"Warning: Unknown category ID {category_id} in {individual_ann_path}. Skipping annotation.")
                    continue

                # 4.g.v. Create a new dictionary for the COCO annotation
                coco_annotations.append({
                    'id': annotation_id_counter, # Assign unique annotation ID
                    'image_id': img_dict['id'],
                    'category_id': category_id,
                    'bbox': coco_bbox,
                    'area': area,
                    'iscrowd': 0 # Typically 0 for object detection
                })
                # Increment the annotation ID counter
                annotation_id_counter += 1
            else:
                # print(f"Warning: Skipping non-rectangle or malformed annotation in {individual_ann_path}") # Too verbose
                pass

    except Exception as e:
        print(f"Error processing individual annotation for {img_filename} ({individual_ann_path}): {e}. Skipping annotations for this image.")

print(f"Processed {len(coco_images)} images and {len(coco_annotations)} annotations.")

"""**Reasoning**:
The next step is to assemble the final COCO dataset dictionary using the populated lists (`coco_images`, `coco_annotations`, `coco_categories`) and then print a summary to verify the assembled data.


"""

coco_dataset = {
    'info': {
        'description': 'Road Damage Dataset in COCO format',
        'version': '1.0',
        'year': datetime.datetime.now().year,
        'contributor': 'Colab DSA',
        'date_created': datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    },
    'licenses': [], # You can add license info if available
    'images': coco_images,
    'annotations': coco_annotations,
    'categories': coco_categories
}

print(f"\n--- COCO Dataset Summary ---")
print(f"Total images in COCO dataset: {len(coco_dataset['images'])}")
print(f"Total annotations in COCO dataset: {len(coco_dataset['annotations'])}")
print(f"Total categories in COCO dataset: {len(coco_dataset['categories'])}")
print(f"--- End COCO Dataset Summary ---")

"""## Save COCO Dataset to JSON File

### Subtask:
Save the `coco_dataset` dictionary, which contains all the images, annotations, and category information in COCO format, into a JSON file named `road_damage_coco.json`.
"""

output_coco_file = 'road_damage_coco.json'

with open(output_coco_file, 'w') as f:
    json.dump(coco_dataset, f, indent=4)

print(f"COCO dataset successfully saved to {output_coco_file}")

# Optionally, display the first few lines of the saved JSON file
# with open(output_coco_file, 'r') as f:
#     for i, line in enumerate(f):
#         if i >= 10:  # Display first 10 lines
#             break
#         print(line, end='')

"""# Task
Split the `road_damage_coco.json` dataset into training, validation, and test subsets.

## Dataset Splitting

### Subtask:
Split the COCO-formatted dataset (e.g., `road_damage_coco.json`) into training, validation, and test subsets.

**Reasoning**:
The first step is to load the previously saved `road_damage_coco.json` file into a Python dictionary to begin the dataset splitting process.
"""

import json
from sklearn.model_selection import train_test_split
from pathlib import Path

# 1. Load the road_damage_coco.json file
output_coco_file = 'road_damage_coco.json'

with open(output_coco_file, 'r') as f:
    coco_data = json.load(f)

print(f"Loaded COCO dataset from {output_coco_file}. It contains {len(coco_data['images'])} images and {len(coco_data['annotations'])} annotations.")

"""**Reasoning**:
Now that the COCO dataset is loaded, the next step is to extract all unique image IDs and then split them into training, validation, and test sets using the specified 80/10/10 ratio. This will ensure that all annotations for a given image stay within the same split.

# Task
Split the COCO-formatted dataset "road_damage_coco.json" into training, validation, and test subsets with a 70% / 15% / 15% ratio.

## Dataset Splitting (70/15/15)

### Subtask:
Split the COCO-formatted dataset (road_damage_coco.json) into training, validation, and test subsets with a 70% / 15% / 15% ratio.

**Reasoning**:
The subtask requires splitting the dataset into training, validation, and test subsets based on image IDs. This step extracts all unique image IDs and performs the 70/15/15 split using `train_test_split` twice.
"""

import numpy as np

# 1. Extract all unique image IDs
all_image_ids = [img['id'] for img in coco_data['images']]

# 2. Perform the initial split (70% train, 30% for val/test combined)
train_image_ids, val_test_image_ids = train_test_split(
    all_image_ids, test_size=0.30, random_state=42
)

# 3. Further split the temporary combined validation/test image IDs (15% val, 15% test)
val_image_ids, test_image_ids = train_test_split(
    val_test_image_ids, test_size=0.50, random_state=42
)

print(f"Total images: {len(all_image_ids)}")
print(f"Training images: {len(train_image_ids)}")
print(f"Validation images: {len(val_image_ids)}")
print(f"Test images: {len(test_image_ids)}")

"""## Dataset Splitting (70/15/15)

### Subtask:
Filter the loaded COCO dataset to create separate COCO JSON structures for training, validation, and test subsets based on the previously determined image IDs, and save them to individual JSON files.

**Reasoning**:
To fulfill the subtask, I need to create a function that filters the original COCO dataset based on provided image IDs. This function will then be used to generate the training, validation, and test subsets and save them to separate JSON files.
"""

import json
import datetime

def create_coco_subset(image_ids, original_coco_data):
    """
    Filters the original COCO dataset to create a subset based on a list of image IDs.
    """
    # Filter images
    subset_images = [img for img in original_coco_data['images'] if img['id'] in image_ids]

    # Filter annotations
    subset_annotations = [ann for ann in original_coco_data['annotations'] if ann['image_id'] in image_ids]

    # Create the subset COCO dictionary
    subset_coco_data = {
        'info': original_coco_data.get('info', {
            'description': 'COCO Subset',
            'version': '1.0',
            'year': datetime.datetime.now().year,
            'contributor': 'Colab DSA',
            'date_created': datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }),
        'licenses': original_coco_data.get('licenses', []),
        'images': subset_images,
        'annotations': subset_annotations,
        'categories': original_coco_data['categories']
    }
    return subset_coco_data

# 1. Generate the training, validation, and test COCO datasets
coco_train = create_coco_subset(train_image_ids, coco_data)
coco_val = create_coco_subset(val_image_ids, coco_data)
coco_test = create_coco_subset(test_image_ids, coco_data)

print(f"Training set: {len(coco_train['images'])} images, {len(coco_train['annotations'])} annotations")
print(f"Validation set: {len(coco_val['images'])} images, {len(coco_val['annotations'])} annotations")
print(f"Test set: {len(coco_test['images'])} images, {len(coco_test['annotations'])} annotations")

# 2. Save each subset to a separate JSON file
output_dir = Path('./') # Assuming current directory for output

with open(output_dir / 'road_damage_coco_train.json', 'w') as f:
    json.dump(coco_train, f, indent=4)
print(f"Saved road_damage_coco_train.json")

with open(output_dir / 'road_damage_coco_val.json', 'w') as f:
    json.dump(coco_val, f, indent=4)
print(f"Saved road_damage_coco_val.json")

with open(output_dir / 'road_damage_coco_test.json', 'w') as f:
    json.dump(coco_test, f, indent=4)
print(f"Saved road_damage_coco_test.json")

"""## Preprocessing for YOLOv8

### Subtask:
Convert COCO annotations to YOLO's native TXT format for training, validation, and test datasets, and create a dataset.yaml configuration file.

**Reasoning**:
The subtask requires converting COCO annotations to YOLO format. The first step is to define the input COCO JSON file paths, the output YOLO directory, and create a consistent mapping from original COCO category IDs to 0-indexed YOLO class IDs.
"""

import json
from pathlib import Path
import shutil

# 1. Define input COCO JSON file paths and output YOLO directory
output_coco_file_train = 'road_damage_coco_train.json'
output_coco_file_val = 'road_damage_coco_val.json'
output_coco_file_test = 'road_damage_coco_test.json'

YOLO_DATA_BASE_DIR = Path('yolov8_data')

# Ensure the base YOLO directory exists
YOLO_DATA_BASE_DIR.mkdir(parents=True, exist_ok=True)

# Load one of the COCO files to extract categories for mapping
with open(output_coco_file_train, 'r') as f:
    coco_train_data = json.load(f)

# 2. Create a consistent mapping from original COCO category IDs to new 0-indexed YOLO class IDs
# We'll also store the class names for the dataset.yaml file
coco_categories = coco_train_data['categories']

original_id_to_yolo_id = {}
yolo_class_names = []

for i, cat in enumerate(coco_categories):
    original_id_to_yolo_id[cat['id']] = i
    yolo_class_names.append(cat['name'])

print(f"YOLO class mapping: {original_id_to_yolo_id}")
print(f"YOLO class names: {yolo_class_names}")

# Prepare a list of datasets to process
dataset_splits = {
    'train': output_coco_file_train,
    'val': output_coco_file_val,
    'test': output_coco_file_test
}

"""**Reasoning**:
The next step is to iterate through each dataset split (train, val, test), create necessary directories, copy images, and convert COCO annotations to YOLO format, saving them as .txt files in the respective 'labels' directories.


"""

IMG_DIR_SOURCE = IMG_DIR # Use the previously detected image directory as source

def convert_coco_to_yolo_split(coco_json_path, split_name, img_source_dir, yolo_base_dir, id_mapping):
    """
    Converts COCO annotations for a single split to YOLO format.
    """
    print(f"\nProcessing {split_name} split...")
    with open(coco_json_path, 'r') as f:
        coco_data_split = json.load(f)

    # Create directories for images and labels
    split_images_dir = yolo_base_dir / split_name / 'images'
    split_labels_dir = yolo_base_dir / split_name / 'labels'

    split_images_dir.mkdir(parents=True, exist_ok=True)
    split_labels_dir.mkdir(parents=True, exist_ok=True)

    # Create a mapping from image_id to image info (width, height, file_name)
    image_id_to_info = {img['id']: {'width': img['width'], 'height': img['height'], 'file_name': img['file_name']}
                        for img in coco_data_split['images']}

    # Group annotations by image_id
    annotations_by_image = defaultdict(list)
    for ann in coco_data_split['annotations']:
        annotations_by_image[ann['image_id']].append(ann)

    total_images_processed = 0
    total_annotations_processed = 0

    for img_id, img_info in image_id_to_info.items():
        original_image_filename = img_info['file_name']
        image_width = img_info['width']
        image_height = img_info['height']

        # Copy image file
        source_image_path = img_source_dir / original_image_filename
        dest_image_path = split_images_dir / original_image_filename
        if source_image_path.is_file():
            shutil.copy(source_image_path, dest_image_path)
            total_images_processed += 1
        else:
            print(f"Warning: Image file not found for {original_image_filename} at {source_image_path}. Skipping.")
            continue

        # Prepare YOLO label file
        label_filename = Path(original_image_filename).stem + '.txt'
        label_file_path = split_labels_dir / label_filename

        with open(label_file_path, 'w') as f_label:
            for ann in annotations_by_image.get(img_id, []):
                x_coco, y_coco, w_coco, h_coco = ann['bbox']
                class_id_coco = ann['category_id']

                # Convert to YOLO format
                x_center = (x_coco + w_coco / 2) / image_width
                y_center = (y_coco + h_coco / 2) / image_height
                bbox_width_norm = w_coco / image_width
                bbox_height_norm = h_coco / image_height

                # Map to YOLO 0-indexed class ID
                yolo_class_id = id_mapping.get(class_id_coco)

                if yolo_class_id is not None:
                    f_label.write(f"{yolo_class_id} {x_center} {y_center} {bbox_width_norm} {bbox_height_norm}\n")
                    total_annotations_processed += 1
                else:
                    print(f"Warning: Category ID {class_id_coco} not found in mapping for image {original_image_filename}. Skipping annotation.")

    print(f"  Copied {total_images_processed} images.")
    print(f"  Processed {total_annotations_processed} annotations.")


# Process each split
for split_name, coco_path in dataset_splits.items():
    convert_coco_to_yolo_split(coco_path, split_name, IMG_DIR_SOURCE, YOLO_DATA_BASE_DIR, original_id_to_yolo_id)

"""**Reasoning**:
The final step is to create the `dataset.yaml` configuration file for YOLO, defining the paths to the training and validation image directories, the number of classes, and their names, as specified in the subtask.


"""

import yaml

# 4. Create a dataset.yaml file
dataset_yaml_path = YOLO_DATA_BASE_DIR / 'dataset.yaml'

dataset_config = {
    'path': str(YOLO_DATA_BASE_DIR.resolve()), # Absolute path to the YOLO data directory
    'train': 'train/images',
    'val': 'val/images',
    'test': 'test/images', # Optional, but good practice if a test set is used for evaluation
    'nc': len(yolo_class_names),
    'names': yolo_class_names
}

with open(dataset_yaml_path, 'w') as f:
    yaml.dump(dataset_config, f, sort_keys=False)

print(f"dataset.yaml created successfully at {dataset_yaml_path}")

"""## Train YOLOv8 Model

### Subtask:
Initiate training for a YOLOv8 model using the prepared dataset.

## Evaluate YOLOv8 Model

### Subtask:
Evaluate the trained YOLOv8 model on the test dataset and display its performance metrics.

**Reasoning**:
To evaluate the YOLOv8 model, we need to load the best weights obtained during training and then run the `val()` method on the test set. The `val()` method will compute and display standard object detection metrics such as mAP (Mean Average Precision).
"""

from ultralytics import YOLO
import os

# The model should already be loaded as 'loaded_model' from a previous cell (dbca1bde).
# If this cell is run independently, uncomment the following lines to load the model.
# model_path = 'runs/detect/yolov8_road_damage_detection6/weights/best.pt'
# if not os.path.exists(model_path):
#     raise FileNotFoundError(f"❌ Trained YOLOv8 model weights not found at {model_path}. Please check the path.")
# loaded_model = YOLO(model_path)

# 2. Use the already loaded YOLOv8 model for evaluation
print("Starting YOLOv8 model evaluation on the test set...")
# Use 'loaded_model' instead of 'model' if it's already loaded
metrics = loaded_model.val()  # No need to specify data path if already set in dataset.yaml

# 3. Print key metrics
print("\nYOLOv8 Evaluation Results:")
print(f"  mAP50-95: {metrics.box.map:.3f}")
print(f"  mAP50: {metrics.box.map50:.3f}")
print(f"  mAP75: {metrics.box.map75:.3f}")

# You can access per-class metrics as well if needed
# print(metrics.box.p) # Precision
# print(metrics.box.r) # Recall
# print(metrics.box.ap_class_index) # Class indices
# print(metrics.box.ap) # Average Precision per class

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np
import json
from pathlib import Path

# Re-derive yolo_class_names (as it might be lost after kernel restart or out-of-order execution)
output_coco_file_train = 'road_damage_coco_train.json'
with open(output_coco_file_train, 'r') as f:
    coco_train_data_for_classes = json.load(f)
coco_categories = coco_train_data_for_classes['categories']
yolo_class_names = [cat['name'] for cat in coco_categories]

# 4. Perform predictions on the selected images
print("\nPerforming predictions on selected images...")
results = loaded_model.predict(source=full_image_paths, conf=0.25, iou=0.7, verbose=False)

# 5. Display the prediction results for each image
for i, result in enumerate(results):
    image_path = full_image_paths[i]

    # Load the original image
    img = Image.open(image_path).convert("RGB")
    img_width, img_height = img.size

    # Prepare for plotting
    fig, ax = plt.subplots(1, figsize=(12, 8))
    ax.imshow(img)
    ax.set_title(f"Predictions for: {Path(image_path).name}")

    # Extract bounding boxes, class IDs, and confidence scores
    # 'boxes' attribute directly provides xyxy, conf, and cls
    if result.boxes and len(result.boxes.xyxy) > 0:
        for j, box in enumerate(result.boxes):
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy().astype(int)
            conf = box.conf[0].cpu().numpy()
            cls_id = int(box.cls[0].cpu().numpy())

            # Convert to [x, y, width, height] for matplotlib.patches.Rectangle
            bbox_x = x1
            bbox_y = y1
            bbox_width = x2 - x1
            bbox_height = y2 - y1

            # Get class name from yolo_class_names list (0-indexed)
            class_name = yolo_class_names[cls_id] if cls_id < len(yolo_class_names) else f"Unknown Class {cls_id}"

            # Draw bounding box
            rect = patches.Rectangle((bbox_x, bbox_y), bbox_width, bbox_height,
                                     linewidth=2, edgecolor='red', facecolor='none')
            ax.add_patch(rect)

            # Add label and confidence
            label_text = f"{class_name} {conf:.2f}"
            ax.text(bbox_x, bbox_y - 10, label_text, color='white',
                    bbox=dict(facecolor='red', alpha=0.7, edgecolor='none', pad=2), fontsize=9)
    else:
        ax.text(10, 10, "No detections", color='yellow', bbox=dict(facecolor='black', alpha=0.7), fontsize=12)

    ax.axis('off')
    plt.show()

print("\nFinished displaying predictions.")

print("\nPer-Class Precision and Recall:")
for i, class_name in enumerate(yolo_class_names):
    precision = metrics.box.p[i] if i < len(metrics.box.p) else 'N/A'
    recall = metrics.box.r[i] if i < len(metrics.box.r) else 'N/A'
    print(f"  Class '{class_name}': Precision={precision:.3f}, Recall={recall:.3f}")

"""**Reasoning**:
To load the best performing YOLOv8 model, I need to import the `YOLO` class, specify the path to the weights, check for its existence, and then instantiate the model.


"""

from ultralytics import YOLO
import os

# 1. Define the path to the trained model's best weights
# This path is based on the previous training run's output.
# The training run created 'yolov8_road_damage_detection6' folder.
model_path = 'runs/detect/yolov8_road_damage_detection6/weights/best.pt'

# 2. Check if the model weights file exists
if not os.path.exists(model_path):
    raise FileNotFoundError(f"❌ Trained YOLOv8 model weights not found at {model_path}. Please check the path and ensure training was successful.")

# 3. Load the trained YOLOv8 model
print(f"Loading trained YOLOv8 model from {model_path}...")
loaded_model = YOLO(model_path)

print("YOLOv8 model loaded successfully.")

"""**Reasoning**:
With the model loaded, the next step is to select a few random image paths from the `coco_test` dataset. This involves loading the `coco_test` JSON file, extracting image filenames, and then randomly sampling them.


"""

import json
import random
from pathlib import Path

# Re-define IMG_DIR as it seems to have been lost in the kernel state
# This path should be consistent with where the images were extracted.
# Based on previous cells, IMG_DIR was detected as /content/road_damage_dataset/ds0/img
IMG_DIR = Path('/content/road_damage_dataset/ds0/img')

# 1. Load the coco_test.json file
# Assuming coco_test.json was saved in the current directory
test_coco_path = 'road_damage_coco_test.json'

if not Path(test_coco_path).is_file():
    raise FileNotFoundError(f"❌ Test COCO JSON file not found at {test_coco_path}. Ensure it exists.")

with open(test_coco_path, 'r') as f:
    coco_test_data = json.load(f)

# 2. Extract image file paths from the test dataset
test_image_files = [img['file_name'] for img in coco_test_data['images']]

# 3. Select a few random image file paths for inference
num_images_to_predict = 5  # Adjust as needed
random_image_paths = random.sample(test_image_files, min(num_images_to_predict, len(test_image_files)))

# Construct full paths for these images using IMG_DIR
full_image_paths = [str(IMG_DIR / fname) for fname in random_image_paths]

print(f"Selected {len(full_image_paths)} random images for prediction:")
for path in full_image_paths:
    print(f"- {path}")

"""**Reasoning**:
Now that the model is loaded and random image paths have been selected, the next step is to perform inference (predictions) on these images using the loaded YOLOv8 model and display the results.


"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np

# 4. Perform predictions on the selected images
print("\nPerforming predictions on selected images...")
results = loaded_model.predict(source=full_image_paths, conf=0.25, iou=0.7, verbose=False)

# 5. Display the prediction results for each image
for i, result in enumerate(results):
    image_path = full_image_paths[i]

    # Load the original image
    img = Image.open(image_path).convert("RGB")
    img_width, img_height = img.size

    # Prepare for plotting
    fig, ax = plt.subplots(1, figsize=(12, 8))
    ax.imshow(img)
    ax.set_title(f"Predictions for: {Path(image_path).name}")

    # Extract bounding boxes, class IDs, and confidence scores
    # 'boxes' attribute directly provides xyxy, conf, and cls
    if result.boxes and len(result.boxes.xyxy) > 0:
        for j, box in enumerate(result.boxes):
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy().astype(int)
            conf = box.conf[0].cpu().numpy()
            cls_id = int(box.cls[0].cpu().numpy())

            # Convert to [x, y, width, height] for matplotlib.patches.Rectangle
            bbox_x = x1
            bbox_y = y1
            bbox_width = x2 - x1
            bbox_height = y2 - y1

            # Get class name from yolo_class_names list (0-indexed)
            class_name = yolo_class_names[cls_id] if cls_id < len(yolo_class_names) else f"Unknown Class {cls_id}"

            # Draw bounding box
            rect = patches.Rectangle((bbox_x, bbox_y), bbox_width, bbox_height,
                                     linewidth=2, edgecolor='red', facecolor='none')
            ax.add_patch(rect)

            # Add label and confidence
            label_text = f"{class_name} {conf:.2f}"
            ax.text(bbox_x, bbox_y - 10, label_text, color='white',
                    bbox=dict(facecolor='red', alpha=0.7, edgecolor='none', pad=2), fontsize=9)
    else:
        ax.text(10, 10, "No detections", color='yellow', bbox=dict(facecolor='black', alpha=0.7), fontsize=12)

    ax.axis('off')
    plt.show()

print("\nFinished displaying predictions.")
